/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kyle Pacana
 */
public class CustomerAccountFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerAccountFrame.class.getName());
// Database connection parameters
    private static final String URL = "jdbc:mysql://localhost:3306/banking_db";
    private static final String USER = "root";
    private static final String PASSWORD = "bardlover"; // Add your MySQL password here if you have one

    /**
     * Establishes a raw connection to the local MySQL database instance.
     */
    private java.sql.Connection getConnection() throws java.sql.SQLException {
        try {
            // Explicitly load the MySQL JDBC driver class
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.err.println("MySQL Driver not found: " + e.getMessage());
        }
        return java.sql.DriverManager.getConnection(URL, USER, PASSWORD);
    }
    /**
     * Creates new form CustomerAccountFrame
     */
    public CustomerAccountFrame() {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (Exception ignored) {}
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlHeader = new javax.swing.JPanel();
        pnlHeaderActions = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnTransactions = new javax.swing.JButton();
        btnViewLogs = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        splitMain = new javax.swing.JSplitPane();
        pnlForm = new javax.swing.JPanel();
        lblAccountNum = new javax.swing.JLabel();
        txtAccountNum = new javax.swing.JTextField();
        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        lblAccountType = new javax.swing.JLabel();
        cmbAccountType = new javax.swing.JComboBox<>();
        lblBalance = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        pnlButtons = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        pnlTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccounts = new javax.swing.JTable();
        pnlSearch = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(18, 18, 18));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        pnlHeaderActions.setBackground(new java.awt.Color(18, 18, 18));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(240, 240, 240));
        lblTitle.setText("CUSTOMER & ACCOUNT MANAGEMENT");
        lblTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 0));
        pnlHeaderActions.add(lblTitle);

        btnTransactions.setText("Go to Transactions");
        btnTransactions.addActionListener(this::btnTransactionsActionPerformed);
        pnlHeaderActions.add(btnTransactions);

        btnViewLogs.setText("View Transaction Logs");
        btnViewLogs.addActionListener(this::btnViewLogsActionPerformed);
        pnlHeaderActions.add(btnViewLogs);

        pnlHeader.add(pnlHeaderActions, java.awt.BorderLayout.EAST);

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlCenter.setBackground(new java.awt.Color(28, 28, 28));
        pnlCenter.setLayout(new java.awt.BorderLayout());

        splitMain.setToolTipText("");

        pnlForm.setBackground(new java.awt.Color(28, 28, 28));
        pnlForm.setLayout(new java.awt.GridBagLayout());

        lblAccountNum.setForeground(new java.awt.Color(255, 255, 255));
        lblAccountNum.setText("Account Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        pnlForm.add(lblAccountNum, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        pnlForm.add(txtAccountNum, gridBagConstraints);

        lblCustomerName.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomerName.setText("Customer Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        pnlForm.add(lblCustomerName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        pnlForm.add(txtCustomerName, gridBagConstraints);

        lblAccountType.setForeground(new java.awt.Color(242, 242, 242));
        lblAccountType.setText("Account Type:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        pnlForm.add(lblAccountType, gridBagConstraints);

        cmbAccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Savings", "Checking" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        pnlForm.add(cmbAccountType, gridBagConstraints);

        lblBalance.setForeground(new java.awt.Color(242, 242, 242));
        lblBalance.setText("Initial Balance:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        pnlForm.add(lblBalance, gridBagConstraints);

        txtBalance.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
        pnlForm.add(txtBalance, gridBagConstraints);

        pnlButtons.setOpaque(false);
        pnlButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnSave.setText("Save Account");
        btnSave.addActionListener(this::btnSaveActionPerformed);
        pnlButtons.add(btnSave);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        pnlButtons.add(btnUpdate);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        pnlButtons.add(btnDelete);

        btnClear.setText("Clear Form");
        btnClear.addActionListener(this::btnClearActionPerformed);
        pnlButtons.add(btnClear);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 5, 15);
        pnlForm.add(pnlButtons, gridBagConstraints);

        splitMain.setLeftComponent(pnlForm);

        pnlTable.setBackground(new java.awt.Color(28, 28, 28));
        pnlTable.setLayout(new java.awt.BorderLayout());

        tblAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Account Number", "Customer Name", "Account Type", "Balance"
            }
        ));
        tblAccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAccountsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAccounts);

        pnlTable.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlSearch.setBackground(new java.awt.Color(18, 18, 16));
        pnlSearch.setOpaque(false);
        pnlSearch.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Search Account:");
        pnlSearch.add(jLabel1);

        txtSearch.setColumns(15);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        pnlSearch.add(txtSearch);

        pnlTable.add(pnlSearch, java.awt.BorderLayout.NORTH);

        splitMain.setRightComponent(pnlTable);

        pnlCenter.add(splitMain, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
txtAccountNum.setEditable(true);
txtAccountNum.setText("");
        txtCustomerName.setText("");
        txtBalance.setText("");
        
        // Reset the account selection dropdown back to the first item (Savings)
        cmbAccountType.setSelectedIndex(0);
        
        // Return your cursor focus back to the account number box for quick typing
        txtAccountNum.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String accountNum = txtAccountNum.getText().trim();
        String name = txtCustomerName.getText().trim();
        String type = cmbAccountType.getSelectedItem().toString();
        String balanceStr = txtBalance.getText().trim();

        if (accountNum.isEmpty() || name.isEmpty() || balanceStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill out all fields!", "Validation Warning", java.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double balance = Double.parseDouble(balanceStr);
            String sql = "INSERT INTO accounts (account_number, customer_name, account_type, balance) VALUES (?, ?, ?, ?)";
            
            try (java.sql.Connection conn = getConnection();
                 java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
                
                pstmt.setString(1, accountNum);
                pstmt.setString(2, name);
                pstmt.setString(3, type);
                pstmt.setDouble(4, balance);
                
                pstmt.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Account saved successfully!");
                
                loadTableData(); // Refresh spreadsheet
                btnClearActionPerformed(evt); // Clear inputs
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Balance must be a valid decimal number!", "Input Error", java.swing.JOptionPane.ERROR_MESSAGE);
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "SQL Error", java.sql.SQLException.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblAccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAccountsMouseClicked
      int selectedRow = tblAccounts.getSelectedRow();
    if (selectedRow != -1) {
        // Retrieve columns from table model and bind them to the form inputs
        txtAccountNum.setText(tblAccounts.getValueAt(selectedRow, 0).toString());
        txtCustomerName.setText(tblAccounts.getValueAt(selectedRow, 1).toString());
        cmbAccountType.setSelectedItem(tblAccounts.getValueAt(selectedRow, 2).toString());
        txtBalance.setText(tblAccounts.getValueAt(selectedRow, 3).toString());
        
        // Disable editing the Primary Key field (Account Number) during updates
        txtAccountNum.setEditable(false);
    }
    }//GEN-LAST:event_tblAccountsMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
      String accountNum = txtAccountNum.getText().trim();
    String name = txtCustomerName.getText().trim();
    String type = cmbAccountType.getSelectedItem().toString();
    String balanceStr = txtBalance.getText().trim();

    if (accountNum.isEmpty() || name.isEmpty() || balanceStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an account row first and modify fields!", "Validation Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        double balance = Double.parseDouble(balanceStr);
        String sql = "UPDATE accounts SET customer_name = ?, account_type = ?, balance = ? WHERE account_number = ?";
        
        try (java.sql.Connection conn = getConnection();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, name);
            pstmt.setString(2, type);
            pstmt.setDouble(3, balance);
            pstmt.setString(4, accountNum);
            
            int rowsUpdated = pstmt.executeUpdate();
            if (rowsUpdated > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Account updated successfully!");
                loadTableData(); // Refresh UI view
                btnClearActionPerformed(evt); // Clear inputs and restore fields
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Account number not found.", "Update Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Balance must be a valid decimal number!", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "SQL Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       String accountNum = txtAccountNum.getText().trim();

    if (accountNum.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an account row from the table to delete!", "Validation Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirmation = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you absolutely sure you want to delete Account " + accountNum + "?", 
            "Confirm Deletion", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);

    if (confirmation == javax.swing.JOptionPane.YES_OPTION) {
        String sql = "DELETE FROM accounts WHERE account_number = ?";
        
        try (java.sql.Connection conn = getConnection();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, accountNum);
            
            int rowsDeleted = pstmt.executeUpdate();
            if (rowsDeleted > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Account deleted successfully!");
                loadTableData(); // Refresh UI view
                btnClearActionPerformed(evt); // Reset form state
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "SQL Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
       String keyword = txtSearch.getText().trim();
    
    // Create a new table model structure
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
        new Object[][] {}, 
        new String[] {"Account Number", "Customer Name", "Account Type", "Balance"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    // SQL query using LIKE operators to search by account number OR customer name
    String query = "SELECT * FROM accounts WHERE account_number LIKE ? OR customer_name LIKE ?";

    try (java.sql.Connection conn = getConnection();
         java.sql.PreparedStatement pstmt = conn.prepareStatement(query)) {
        
        // Use wildcards (%) for partial matching (e.g., typing "K" will match "Kyle")
        pstmt.setString(1, "%" + keyword + "%");
        pstmt.setString(2, "%" + keyword + "%");
        
        try (java.sql.ResultSet rs = pstmt.executeQuery()) {
            while (rs.next()) {
                String accountNum = rs.getString("account_number");
                String name = rs.getString("customer_name");
                String type = rs.getString("account_type");
                double balance = rs.getDouble("balance");

                model.addRow(new Object[]{accountNum, name, type, balance});
            }
        }
        
        // Bind the filtered results to your table component
        tblAccounts.setModel(model);

    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error filtering data: " + e.getMessage(), 
            "Search Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionsActionPerformed
     this.dispose();
    
    // Open the Transactions window
    java.awt.EventQueue.invokeLater(() -> {
        new TransactionFrame().setVisible(true);
    });
    }//GEN-LAST:event_btnTransactionsActionPerformed

    private void btnViewLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLogsActionPerformed
      this.dispose(); 
    
    // Open and display the new Transaction Log frame
    java.awt.EventQueue.invokeLater(() -> {
        new TransactionLogFrame().setVisible(true);
    });
    }//GEN-LAST:event_btnViewLogsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerAccountFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTransactions;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewLogs;
    private javax.swing.JComboBox<String> cmbAccountType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccountNum;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHeaderActions;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JSplitPane splitMain;
    private javax.swing.JTable tblAccounts;
    private javax.swing.JTextField txtAccountNum;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
// =========================================================================
    // CUSTOM DATABASE LOGIC METHODS
    // =========================================================================

    /**
     * Pulls live account rows from your database and populates the table.
     */
    private void loadTableData() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Account Number", "Customer Name", "Account Type", "Balance"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Prevents manual editing inside cells
            }
        };

        String query = "SELECT * FROM accounts";

        try (java.sql.Connection conn = getConnection();
             java.sql.Statement stmt = conn.createStatement();
             java.sql.ResultSet rs = stmt.executeQuery(query)) {

            while (rs.next()) {
                String accountNum = rs.getString("account_number");
                String name = rs.getString("customer_name");
                String type = rs.getString("account_type");
                double balance = rs.getDouble("balance");

                model.addRow(new Object[]{accountNum, name, type, balance});
            }

            tblAccounts.setModel(model);

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error loading data from database: " + e.getMessage(), 
                "Database Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

}