/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import javax.swing.UIManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Kyle Pacana
 */
public class TransactionFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransactionFrame.class.getName());

    /**
     * Creates new form TransactionFrame
     */
    public TransactionFrame() {
        try {
        UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
    } catch (Exception ignored) {}
        initComponents();
        
    
    jPanel3.setBackground(new Color(18, 18, 18));
    jPanel4.setBackground(new Color(28, 28, 28));
    
    // 4. Match the custom styling of your input fields to your main frame
    tfAccountId.setBackground(new Color(38, 38, 38));
    tfAccountId.setForeground(new Color(240, 240, 240));
    tfAccountId.setCaretColor(Color.WHITE);
    
    tfAmount.setBackground(new Color(38, 38, 38));
    tfAmount.setForeground(new Color(240, 240, 240));
    tfAmount.setCaretColor(Color.WHITE);
    
    cbTxnType.setBackground(new Color(38, 38, 38));
    cbTxnType.setForeground(new Color(240, 240, 240));
    
    btnSubmit.setBackground(new Color(230, 230, 230));
    btnSubmit.setForeground(new Color(18, 18, 18));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblAccountId = new javax.swing.JLabel();
        tfAccountId = new javax.swing.JTextField();
        lblTxnType = new javax.swing.JLabel();
        cbTxnType = new javax.swing.JComboBox<>();
        lblAmount = new javax.swing.JLabel();
        tfAmount = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(18, 18, 18));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(28, 28, 28));

        lblAccountId.setForeground(new java.awt.Color(240, 240, 240));
        lblAccountId.setText("TARGET ACCOUNT ID:");

        lblTxnType.setForeground(new java.awt.Color(240, 240, 240));
        lblTxnType.setText("TRANSACTION TYPE:");

        cbTxnType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deposit", "Withdrawal" }));

        lblAmount.setForeground(new java.awt.Color(240, 240, 240));
        lblAmount.setText("AMOUNT (₱):");

        tfAmount.setText("0.00");
        tfAmount.addActionListener(this::tfAmountActionPerformed);

        btnSubmit.setText("EXECUTE TRANSACTION");
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);

        btnBack.setText("← Back to Customer Management");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAmount)
                                    .addComponent(lblTxnType)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblAccountId)))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfAccountId)
                            .addComponent(cbTxnType, 0, 131, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnSubmit)))
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountId)
                    .addComponent(tfAccountId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTxnType)
                    .addComponent(cbTxnType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnBack))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAmountActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
                                          
    String accNum = tfAccountId.getText().trim();
        String amtStr = tfAmount.getText().trim();
        String type = (String) cbTxnType.getSelectedItem();

        if (accNum.isEmpty() || amtStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all transaction fields.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double amount;
        try {
            amount = Double.parseDouble(amtStr);
            if (amount <= 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid positive number for the amount.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (Connection conn = DBConnection.getConnection()) {
            conn.setAutoCommit(false); // Enable strict transactional isolation

            // 1. Fetch current balance safely from 'accounts' using account_number
            String checkSql = "SELECT balance FROM accounts WHERE account_number = ?";
            double currentBalance = -1;
            
            try (PreparedStatement psCheck = conn.prepareStatement(checkSql)) {
                psCheck.setString(1, accNum);
                try (ResultSet rs = psCheck.executeQuery()) {
                    if (rs.next()) {
                        currentBalance = rs.getDouble("balance");
                    } else {
                        JOptionPane.showMessageDialog(this, "Account Number not found.", "Error", JOptionPane.ERROR_MESSAGE);
                        conn.rollback();
                        return;
                    }
                }
            }

            // 2. Perform Transaction Math
            double newBalance = currentBalance;
            if ("Deposit".equals(type)) {
                newBalance += amount;
            } else if ("Withdrawal".equals(type)) {
                if (currentBalance < amount) {
                    JOptionPane.showMessageDialog(this, "Insufficient funds available.", "Transaction Denied", JOptionPane.WARNING_MESSAGE);
                    conn.rollback();
                    return;
                }
                newBalance -= amount;
            }

            // 3. Update 'accounts' table info
            String updateSql = "UPDATE accounts SET balance = ? WHERE account_number = ?";
            try (PreparedStatement psUpdate = conn.prepareStatement(updateSql)) {
                psUpdate.setDouble(1, newBalance);
                psUpdate.setString(2, accNum);
                psUpdate.executeUpdate();
            }

            // 4. Log interaction history securely
          // 4. Log interaction history securely
            String logSql = "INSERT INTO Transaction (account_id, transaction_type, amount, transaction_date) VALUES (?, ?, ?, NOW())";
            try (PreparedStatement psLog = conn.prepareStatement(logSql)) {
                psLog.setString(1, accNum);
                psLog.setString(2, type);
                psLog.setDouble(3, amount);
                psLog.executeUpdate();
            }

            conn.commit(); // Push structural updates to storage
            JOptionPane.showMessageDialog(this, "Transaction posted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            // Clear inputs instead of disposing window, allowing consecutive postings
            tfAccountId.setText("");
            tfAmount.setText("0.00");
            cbTxnType.setSelectedIndex(0);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "System Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       this.dispose(); // Close the transaction window
    java.awt.EventQueue.invokeLater(() -> {
        new CustomerAccountFrame().setVisible(true); // Reopen the main table dashboard
    });
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransactionFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbTxnType;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAccountId;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblTxnType;
    private javax.swing.JTextField tfAccountId;
    private javax.swing.JTextField tfAmount;
    // End of variables declaration//GEN-END:variables

}
